### ISSUE TITLE
Wrong generated path for transitive bower (less) resource.

### ISSUE THREAD

**Issue by lisobal** [aetheric/gulp-less-precompiler#19]
I have a dependency to: "bower-bootswatch-paper": "paper-less#*" which has has a transitive dependency on "bootstrap-less". Bootwatch's "paper.less" file explicity imports:
@import "../bower_components/bootstrap-less/less/bootstrap.less";

I reference the "paper.less" resource in one of my less files:
@import '/bower_components/bower-bootswatch-paper/less/paper.less';

However, it can't find the "bootstrap.less" file because the generated path to it is wrong:
"<PROJECT_PATH>\bower_components\bower-bootswatch-paper\bower_components\bootstrap-less\less\bootstrap.less"

**Comment by Tzrlk** [comment]
The fix for this should be straightforward. Just search for bower_components in any path, and replace anything before that with the project root.

**Comment by Tzrlk** [comment]
The build for this passes fine (https://travis-ci.org/aetheric/gulp-less-precompiler/builds/134041991), but the fix itself hasn't been tested. If you want to double-check that it fixes the issue before I merge it, use version `1.2.2-5-g444ece7` of the gulp-less-precompiler.

**Comment by lisobal** [comment]
Yup. This change seems to fix the issue.
